{
    "version": "1.0.0",
    "plays": [
        {
            "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
            "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
            "play": "Get Facts",
            "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
            "play_pattern": "all",
            "name": "Get Facts",
            "pattern": "all",
            "uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
            "__play_name": "Get Facts",
            "tasks": [
                {
                    "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
                    "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
                    "play": "Get Facts",
                    "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
                    "play_pattern": "all",
                    "task": "Gathering Facts",
                    "task_uuid": "c652ca06-eba4-e2b1-2e46-000000000012",
                    "task_action": "gather_facts",
                    "resolved_action": null,
                    "task_args": "",
                    "task_path": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml:2",
                    "host": "juniper1.lab.test",
                    "uuid": "2cad159e-ee9d-4baa-a78b-c62f9940d5b5",
                    "__host": "juniper1.lab.test",
                    "__result": "FAILED",
                    "__changed": false,
                    "__duration": "1s",
                    "__number": 0,
                    "__task": "Gathering Facts",
                    "__task_action": "gather_facts",
                    "remote_addr": "juniper1.lab.test",
                    "res": {
                        "ansible_facts": {},
                        "msg": "The following modules failed to execute: junipernetworks.junos.junos_facts\n",
                        "failed_modules": {
                            "junipernetworks.junos.junos_facts": {
                                "failed": true,
                                "msg": "[Errno -2] Name or service not known",
                                "invocation": {
                                    "module_args": {
                                        "gather_subset": [
                                            "all"
                                        ],
                                        "config_format": "text",
                                        "available_network_resources": false,
                                        "gather_network_resources": null,
                                        "provider": null
                                    }
                                }
                            }
                        },
                        "_ansible_verbose_override": true,
                        "_ansible_no_log": false,
                        "changed": false
                    },
                    "start": "2022-08-23T05:05:09.540302",
                    "end": "2022-08-23T05:05:11.065363",
                    "duration": 1.525061,
                    "ignore_errors": null,
                    "event_loop": null
                },
                {
                    "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
                    "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
                    "play": "Get Facts",
                    "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
                    "play_pattern": "all",
                    "task": "Gathering Facts",
                    "task_uuid": "c652ca06-eba4-e2b1-2e46-000000000012",
                    "task_action": "gather_facts",
                    "resolved_action": null,
                    "task_args": "",
                    "task_path": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml:2",
                    "host": "cisco1.lab.test",
                    "uuid": "4b6e1103-f8b3-458a-ab61-daf4964d4b80",
                    "__host": "cisco1.lab.test",
                    "__result": "FAILED",
                    "__changed": false,
                    "__duration": "2s",
                    "__number": 1,
                    "__task": "Gathering Facts",
                    "__task_action": "gather_facts",
                    "remote_addr": "cisco1.lab.test",
                    "res": {
                        "ansible_facts": {},
                        "msg": "The following modules failed to execute: cisco.ios.ios_facts\n",
                        "failed_modules": {
                            "cisco.ios.ios_facts": {
                                "failed": true,
                                "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname cisco1.lab.test (Name or service not known)",
                                "invocation": {
                                    "module_args": {
                                        "gather_subset": [
                                            "all"
                                        ],
                                        "available_network_resources": false,
                                        "gather_network_resources": null,
                                        "provider": null
                                    }
                                }
                            }
                        },
                        "_ansible_verbose_override": true,
                        "_ansible_no_log": false,
                        "changed": false
                    },
                    "start": "2022-08-23T05:05:09.546607",
                    "end": "2022-08-23T05:05:11.604107",
                    "duration": 2.0575,
                    "ignore_errors": null,
                    "event_loop": null
                },
                {
                    "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
                    "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
                    "play": "Get Facts",
                    "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
                    "play_pattern": "all",
                    "task": "Gathering Facts",
                    "task_uuid": "c652ca06-eba4-e2b1-2e46-000000000012",
                    "task_action": "gather_facts",
                    "resolved_action": null,
                    "task_args": "",
                    "task_path": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml:2",
                    "host": "arista1.lab.test",
                    "uuid": "47e62db6-f3fa-4ad4-b2e8-183df09cbe9c",
                    "__host": "arista1.lab.test",
                    "__result": "FAILED",
                    "__changed": false,
                    "__duration": "2s",
                    "__number": 2,
                    "__task": "Gathering Facts",
                    "__task_action": "gather_facts",
                    "remote_addr": "arista1.lab.test",
                    "res": {
                        "ansible_facts": {},
                        "msg": "The following modules failed to execute: arista.eos.eos_facts\n",
                        "failed_modules": {
                            "arista.eos.eos_facts": {
                                "failed": true,
                                "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname arista1.lab.test (Name or service not known)",
                                "invocation": {
                                    "module_args": {
                                        "gather_subset": [
                                            "all"
                                        ],
                                        "available_network_resources": false,
                                        "gather_network_resources": null,
                                        "provider": null
                                    }
                                }
                            }
                        },
                        "_ansible_verbose_override": true,
                        "_ansible_no_log": false,
                        "changed": false
                    },
                    "start": "2022-08-23T05:05:09.553404",
                    "end": "2022-08-23T05:05:11.898487",
                    "duration": 2.345083,
                    "ignore_errors": null,
                    "event_loop": null
                },
                {
                    "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
                    "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
                    "play": "Get Facts",
                    "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
                    "play_pattern": "all",
                    "task": "Gathering Facts",
                    "task_uuid": "c652ca06-eba4-e2b1-2e46-000000000012",
                    "task_action": "gather_facts",
                    "resolved_action": null,
                    "task_args": "",
                    "task_path": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml:2",
                    "host": "windows1.lab.test",
                    "uuid": "22c1505c-bf28-4378-a17a-f21d2354df21",
                    "__host": "windows1.lab.test",
                    "__result": "FAILED",
                    "__changed": false,
                    "__duration": "0s",
                    "__number": 3,
                    "__task": "Gathering Facts",
                    "__task_action": "gather_facts",
                    "remote_addr": "windows1.lab.test",
                    "res": {
                        "msg": "The module ansible.legacy.setup was redirected to ansible.windows.setup, which could not be loaded.",
                        "_ansible_no_log": false
                    },
                    "start": "2022-08-23T05:05:09.560266",
                    "end": "2022-08-23T05:05:09.575531",
                    "duration": 0.015265,
                    "ignore_errors": null,
                    "event_loop": null
                },
                {
                    "playbook": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml",
                    "playbook_uuid": "4a4ddff9-14a6-4921-be0c-467865cef12c",
                    "play": "Get Facts",
                    "play_uuid": "c652ca06-eba4-e2b1-2e46-00000000000a",
                    "play_pattern": "all",
                    "task": "Gathering Facts",
                    "task_uuid": "c652ca06-eba4-e2b1-2e46-000000000012",
                    "task_action": "gather_facts",
                    "resolved_action": null,
                    "task_args": "",
                    "task_path": "/home/luvalle/aap-testing/playbooks/gather_facts_networking.yml:2",
                    "host": "ubuntu1.lab.test",
                    "uuid": "7f65742e-c0ed-42e5-974a-57ba142a3b6a",
                    "__host": "ubuntu1.lab.test",
                    "__result": "UNREACHABLE",
                    "__changed": false,
                    "__duration": "0s",
                    "__number": 4,
                    "__task": "Gathering Facts",
                    "__task_action": "gather_facts",
                    "remote_addr": "ubuntu1.lab.test",
                    "start": "2022-08-23T05:05:09.566873",
                    "end": "2022-08-23T05:05:09.885818",
                    "duration": 0.318945,
                    "res": {
                        "unreachable": true,
                        "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ubuntu1.lab.test: Name or service not known",
                        "changed": false
                    }
                }
            ],
            "__ok": 0,
            "__skipped": 0,
            "__failed": 4,
            "__unreachable": 1,
            "__ignored": 0,
            "__in_progress": 0,
            "__changed": 0,
            "__task_count": 5,
            "__pcomplete": 100,
            "__progress": "COMPLETE",
            "___progress": "80%"
        }
    ],
    "stdout": [
        "",
        "PLAY [Get Facts] ***************************************************************",
        "",
        "TASK [Gathering Facts] *********************************************************",
        "\u001b[0;31mfatal: [windows1.lab.test]: FAILED! => {\"msg\": \"The module ansible.legacy.setup was redirected to ansible.windows.setup, which could not be loaded.\"}\u001b[0m",
        "\u001b[1;31mfatal: [ubuntu1.lab.test]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: Could not resolve hostname ubuntu1.lab.test: Name or service not known\", \"unreachable\": true}\u001b[0m",
        "\u001b[1;35m[WARNING]: Ignoring timeout(10) for junipernetworks.junos.junos_facts\u001b[0m",
        "\u001b[1;35m[WARNING]: Ignoring timeout(10) for cisco.ios.ios_facts\u001b[0m",
        "\u001b[1;35m[WARNING]: Ignoring timeout(10) for arista.eos.eos_facts\u001b[0m",
        "\u001b[0;31mfatal: [juniper1.lab.test]: FAILED! => {\"ansible_facts\": {}, \"changed\": false, \"failed_modules\": {\"junipernetworks.junos.junos_facts\": {\"failed\": true, \"invocation\": {\"module_args\": {\"available_network_resources\": false, \"config_format\": \"text\", \"gather_network_resources\": null, \"gather_subset\": [\"all\"], \"provider\": null}}, \"msg\": \"[Errno -2] Name or service not known\"}}, \"msg\": \"The following modules failed to execute: junipernetworks.junos.junos_facts\\n\"}\u001b[0m",
        "\u001b[0;31mfatal: [cisco1.lab.test]: FAILED! => {\"ansible_facts\": {}, \"changed\": false, \"failed_modules\": {\"cisco.ios.ios_facts\": {\"failed\": true, \"invocation\": {\"module_args\": {\"available_network_resources\": false, \"gather_network_resources\": null, \"gather_subset\": [\"all\"], \"provider\": null}}, \"msg\": \"ssh connection failed: ssh connect failed: Failed to resolve hostname cisco1.lab.test (Name or service not known)\"}}, \"msg\": \"The following modules failed to execute: cisco.ios.ios_facts\\n\"}\u001b[0m",
        "\u001b[0;31mfatal: [arista1.lab.test]: FAILED! => {\"ansible_facts\": {}, \"changed\": false, \"failed_modules\": {\"arista.eos.eos_facts\": {\"failed\": true, \"invocation\": {\"module_args\": {\"available_network_resources\": false, \"gather_network_resources\": null, \"gather_subset\": [\"all\"], \"provider\": null}}, \"msg\": \"ssh connection failed: ssh connect failed: Failed to resolve hostname arista1.lab.test (Name or service not known)\"}}, \"msg\": \"The following modules failed to execute: arista.eos.eos_facts\\n\"}\u001b[0m",
        "",
        "PLAY RECAP *********************************************************************",
        "\u001b[0;31marista1.lab.test\u001b[0m           : ok=0    changed=0    unreachable=0    \u001b[0;31mfailed=1   \u001b[0m skipped=0    rescued=0    ignored=0   ",
        "\u001b[0;31mcisco1.lab.test\u001b[0m            : ok=0    changed=0    unreachable=0    \u001b[0;31mfailed=1   \u001b[0m skipped=0    rescued=0    ignored=0   ",
        "\u001b[0;31mjuniper1.lab.test\u001b[0m          : ok=0    changed=0    unreachable=0    \u001b[0;31mfailed=1   \u001b[0m skipped=0    rescued=0    ignored=0   ",
        "\u001b[0;31mubuntu1.lab.test\u001b[0m           : ok=0    changed=0    \u001b[1;31munreachable=1   \u001b[0m failed=0    skipped=0    rescued=0    ignored=0   ",
        "\u001b[0;31mwindows1.lab.test\u001b[0m          : ok=0    changed=0    unreachable=0    \u001b[0;31mfailed=1   \u001b[0m skipped=0    rescued=0    ignored=0   "
    ],
    "status": "failed",
    "status_color": 9
}